In [41]:
%pip install numpy

You should consider upgrading via the '/Users/strurphe/iim/calculs-matriciels/.venv/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [42]:
%pip install pandas matplotlib seaborn

You should consider upgrading via the '/Users/strurphe/iim/calculs-matriciels/.venv/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Numpy

In [44]:
first_list = [1, 2, 3, 4]
second_list = [5, 6, 7, 8]

In [45]:
array = np.array([first_list, first_list])

In [46]:
array

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [47]:
array.shape

(2, 4)

In [48]:
array.size

8

In [49]:
array.dtype

dtype('int64')

In [50]:
array_2 = np.array([second_list, second_list])
array_2

array([[5, 6, 7, 8],
       [5, 6, 7, 8]])

In [51]:
array * array_2

array([[ 5, 12, 21, 32],
       [ 5, 12, 21, 32]])

In [52]:
np.matmul(array_2, array.transpose())

array([[70, 70],
       [70, 70]])

In [53]:
np.matmul(array_2.transpose(), array)

array([[10, 20, 30, 40],
       [12, 24, 36, 48],
       [14, 28, 42, 56],
       [16, 32, 48, 64]])

In [54]:
array.mean()

np.float64(2.5)

In [55]:
np.median(array)

np.float64(2.5)

# Pandas

In [56]:
dictionary = {
    "nom": ["Michel", "Jean", "Bernard"],
    "nom de famille": ["Culasse", "Trou", "Hypothermie"],
    "age": [60, 57.2, 50]
}

dictionary_2 = {
    "nom": ["Dylan", "David", "Arthur"],
    "nom de famille": ["Plot", "Machinerie", "Transilien"],
    "age": [1, 2, 3]
}

In [57]:
df = pd.DataFrame.from_dict(dictionary)
df_2 = pd.DataFrame.from_dict(dictionary_2)

In [58]:
df_tot = pd.concat([df, df_2])
df_tot

nom nom de famille   age
0   Michel        Culasse  60.0
1     Jean           Trou  57.2
2  Bernard    Hypothermie  50.0
0    Dylan           Plot   1.0
1    David     Machinerie   2.0
2   Arthur     Transilien   3.0

In [59]:
df_tot = pd.concat([df, df_2], axis=1)
df_tot

nom nom de famille   age     nom nom de famille  age
0   Michel        Culasse  60.0   Dylan           Plot    1
1     Jean           Trou  57.2   David     Machinerie    2
2  Bernard    Hypothermie  50.0  Arthur     Transilien    3

In [60]:
df["vege"] = [True, False, True]
df

nom nom de famille   age   vege
0   Michel        Culasse  60.0   True
1     Jean           Trou  57.2  False
2  Bernard    Hypothermie  50.0   True

In [61]:
df["celib"] = [False, False, False]
df

nom nom de famille   age   vege  celib
0   Michel        Culasse  60.0   True  False
1     Jean           Trou  57.2  False  False
2  Bernard    Hypothermie  50.0   True  False

In [62]:
df = pd.concat([df, pd.DataFrame({"pou": [True, False, True]})], axis=1)
df

nom nom de famille   age   vege  celib    pou
0   Michel        Culasse  60.0   True  False   True
1     Jean           Trou  57.2  False  False  False
2  Bernard    Hypothermie  50.0   True  False   True

# Machine Learning

In [63]:
%pip install scikit-learn

     |████████████████████████████████| 11.1 MB 1.8 MB/s eta 0:00:01
     |████████████████████████████████| 30.3 MB 1.9 MB/s eta 0:00:01
     |████████████████████████████████| 301 kB 2.4 MB/s eta 0:00:01
You should consider upgrading via the '/Users/strurphe/iim/calculs-matriciels/.venv/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [65]:
from sklearn.datasets import load_digits

data, labels = load_digits(return_X_y=True)

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])